baseURL = "/"
languageCode = "en-us"
title = "Eric Treacy"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
rssLimit = 20
timeout = "60s"
paginate = 10
summaryLength = 70
canonifyURLs = true
enableInlineShortcodes = true

[params]
  description = "Personal website of Eric Treacy - Software Engineer, Writer, and Photography Enthusiast"
  author = "Eric Treacy"
  keywords = ["software engineer", "writer", "photography", "blog", "technology", "personal website"]
  images = ["/img/default-share.jpg"]
  mainSections = ["writing", "projects", "photos"]
  twitterHandle = "@erictreacy"
  dateFormat = "January 2, 2006"
  lastmod = true
  readingTime = true
  socialShare = true
  showAuthor = true

[params.seo]
  # Schema.org
  schemaType = "Person"
  schemaName = "Eric Treacy"
  schemaLocale = "en-US"
  schemaImage = "/img/default-share.jpg"
  schemaImageWidth = 1200
  schemaImageHeight = 630
  # Open Graph
  ogLocale = "en_US"
  ogSiteName = "Eric Treacy"
  ogType = "website"
  # Twitter Cards
  twitterCard = "summary_large_image"
  twitterSite = "@erictreacy"
  twitterCreator = "@erictreacy"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[permalinks]
  writing = "/writing/:year/:month/:slug/"
  projects = "/projects/:slug/"
  photos = "/photos/:slug/"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "HEADERS", "SITEMAP"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss+xml"
    baseName = "feed"
  [outputFormats.HEADERS]
    mediatype = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true
  [outputFormats.SITEMAP]
    mediatype = "application/xml"
    baseName = "sitemap"
    isHTML = false
    isPlainText = false
    noUgly = true
    rel = "sitemap"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    noClasses = false
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[security]
  [security.funcs]
    getenv = ["^HUGO_"]
  [security.http]
    methods = ["(?i)GET|POST"]
    urls = [".*"]

[build]
  writeStats = true
  noJSConfigInAssets = true

[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "strict-origin-when-cross-origin"

[minify]
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
      keepEndTags = true
      keepQuotes = false
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 0
    [minify.tdewolff.js]
      precision = 0
      keepVarNames = false
    [minify.tdewolff.json]
      precision = 0
    [minify.tdewolff.svg]
      precision = 0
    [minify.tdewolff.xml]
      keepWhitespace = false

[imaging]
  quality = 85
  anchor = "Smart"
  resampleFilter = "Lanczos"
  [imaging.exif]
    disableDate = true
    disableLatLong = true
    excludeFields = ""
    includeFields = ""

[caches]
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = "720h"
  [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "720h"
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "720h"
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "720h"
  [caches.modules]
    dir = ":cacheDir/modules"
    maxAge = "720h"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.120.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "data"
    target = "data"
