backend:
  name: git-gateway
  branch: main

media_folder: "static/reading" # Based on your memory about image storage
public_folder: "/reading"

collections:
  - name: "writing"
    label: "Writing"
    folder: "content/writing"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "library"
    label: "Library"
    files:
      - name: "books"
        label: "Books"
        file: "data/library.yaml"
        fields:
          - label: "Books"
            name: "books"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Author", name: "author", widget: "string"}
              - {label: "Cover", name: "cover", widget: "image"}
              - {label: "Link", name: "link", widget: "string", required: false}
              - {label: "Notes", name: "notes", widget: "text", required: false}
